[package]
name = "gym-blackjack"
version = "0.1.4"
authors = ["Zeti <admin@zeti.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gym_blackjack"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.3"

[dependencies.pyo3]
version = "0.13.0"
features = []

[profile.dev]
debug = 2