[package]
name = "gym-chess"
version = "0.2.0"
authors = ["Zeti <contact@zeti.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gym_chess"
crate-type = ["staticlib", "cdylib"]

[dependencies]
lazy_static = "1.4.0"

[profile.dev]
debug = 2