[package]
name = "zarena"
version = "0.2.0"
authors = ["zetiworld <zetiapp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "zarena"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
itertools = "0.10.1"
rand = "0.8.4"
pyo3 = { version = "0.15.0", features = ["abi3-py36", "extension-module"] }

[profile.dev]
debug = 2
