[package]
name = "zarena"
version = "0.2.0"
authors = ["zetiworld <zetiapp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "zarena"
crate-type = ["cdylib"]

[features]
wasm = ["wasm-bindgen", "serde"]

[dependencies]
lazy_static = "1.4.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
console_error_panic_hook = "0.1.6"

# [profile.dev]
# debug = 2

[profile.release]
lto = true
opt-level = "s"