name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: actions/checkout@v2
      - run: pip install 'maturin>=0.12,<0.13'
      - run: maturin publish -u __token__ -p ${{ secrets.PYPI_SECRET }}