- name: Python

  on:
    pull_request:
      branches: [ develop, release/*, master ]

  jobs:
    format_and_test:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.7 
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - name: Install poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.12
      - run: poetry --version

      - name: Install dependencies
        run: poetry install && poetry build 
          
      - name: Format with Black
        run: poetry run black .

      - name: Build local package
        run: poetry run maturin develop
          
      - name: Test with pytest
        run: poetry run pytest

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes


- name: Publish

  on:
    push:
      branches: [ master ]

  jobs:
    publish_pypi:
      runs-on: ubuntu-latest
      needs: publish_lib_crate
      steps:
        - name: Publish
          uses: actions/checkout@v2
          run: pip install 'maturin>=0.9.2,<0.10'
          run: maturin publish -u __token__ -p ${{ secrets.PYPI_PASSWORD }}