name: Python

on:
  pull_request:
    branches: [ develop, release/*, master ]

jobs:
  format_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.5

    - name: Install dependencies
      run: poetry build 
        
    - name: Format with Black
      run: black . 
        
    - name: Test with pytest
      run: pytest

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply formatting changes
        branch: ${{ github.head_ref }}

on:
  push:
    branches: [ master ]

jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    needs: publish_lib_crate
    steps:
      - name: Publish
      - uses: actions/checkout@v2
      - run: pip install 'maturin>=0.9.2,<0.10'
      - run: maturin publish -u __token__ -p ${{ secrets.PYPI_PASSWORD }}