name: Rust

on:
  push:
    branches: [ develop, release/*, master ]
  pull_request:
    branches: [ develop, release/*, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
   build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
