name: Rust

on:
  pull_request:
    branches: [ develop, release/*, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
   build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Create Rust ToolChain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Format 
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
      - name: Production Build
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
